function createfigure1(X1, Y1, S1)
%CREATEFIGURE1(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 29-Jul-2017 20:21:24

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,'MarkerEdgeColor','none',...
    'Marker','circle');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 15]);
