function createfigure(X1, Y1, D, Cl, mode, Rate, Payload)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Apr-2017 14:23:47

% Create figure
figure1 = figure('Color',[1 1 1], 'Position', [100 100 400 300]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2.5]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Choose color
if strcmp(mode, 'Host-to-FPGA')
    pCl = Cl{1};
else
    if strcmp(mode, 'End-to-End')
        pCl = Cl{2};
    end
end

% Create plot
%legend_text = strcat('Deadline =', num2str(D) ,'ms');
legend_text = strcat(num2str(Rate) ,' Mbps, ', num2str(Payload), ' Bytes');
plot(X1,Y1,'DisplayName', legend_text,'MarkerEdgeColor',pCl,...
    'MarkerSize',6,...
    'Marker','o',...
    'LineWidth',2,...
    'LineStyle','-',...
    'Color',pCl);
xlim([0 0.6]);

% Create xlabel
if strcmp(mode, 'Host-to-FPGA')
    xlabel({'Measured Host-to-FPGA Latency (ms)'});
else
    if strcmp(mode, 'End-to-End')
        xlabel({'Measured End-to-End Latency (ms)'});
    end
end
% Create ylabel
ylabel({'Empirical CDF'});

% Create legend
legend(axes1,'show');
set(legend,...
    'Position',[0.44625 0.193333333333335 0.43875 0.0716666666666664]);

