function createfigure_multi(X1, Y1, Sample, D, Cl, mode, rate, Payload, Marker, N)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Apr-2017 14:23:47

% Create figure
figure1 = figure('Color',[1 1 1], 'Position', [100 100 400 300]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontSize',15);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2.5]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Choose color
%if strcmp(mode, 'Host-to-FPGA')
%   pCl = Cl{1};
%else
%    if strcmp(mode, 'End-to-End')
%        pCl = Cl{2};
%    end
%end

% Create plot
%legend_text = strcat('Deadline =', num2str(D) ,'ms');

for i=1:N
legend_text = strcat(num2str(rate(i)) , ' Mbps, ', num2str(Payload(i)), ' Bytes');
plot(X1{i}(Sample{i}),Y1{i}(Sample{i}),'DisplayName', legend_text,'MarkerEdgeColor',Cl{i},...
    'MarkerSize',8,...
    'Marker',Marker{i},...
    'LineWidth',2,...
    'LineStyle','-',...
    'Color',Cl{i});
end
xlim([0 2]);

% Create xlabel
if strcmp(mode, 'Host-to-FPGA')
    xlabel({'Measured Host-to-FPGA Latency (ms)'});
else
    if strcmp(mode, 'Round-Trip')
        xlabel({'Measured Round-Trip Latency (ms)'});
    end
end
% Create ylabel
ylabel({'Empirical CDF'});

% Create legend
legend(axes1,'show');
set(legend,...
    'Position',[0.47375 0.206666666666667 0.41625 0.341666666666666]);
