function createfigure_contention_percentage_DCFsat_mobihoc(X1, Y1, X2, Y2, X3, Y3, X4, Y4, myTitle, path)
%CREATEFIGURE2(X1, Y1, X2, YMATRIX1, X3, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 06-May-2018 19:25:49

% Create figure
figure1 = figure('Color',[1 1 1], 'position',[100,100,450,350]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Q-CHAIN','MarkerSize',10,...
    'Marker','square',...
    'LineWidth',2,...
    'Color',[1 0 1]);

plot(X2,Y2,'DisplayName','CHAIN','MarkerSize',10,...
    'Marker','^',...
    'LineWidth',2,...
    'Color',[0 0 1]);

plot(X3,Y3,'DisplayName','QLB-CSMA','MarkerSize',10,...
    'Marker','v',...
    'LineWidth',2,...
    'Color',[0 1 0]);

plot(X4,Y4,'DisplayName','DCF','MarkerSize',10,...
    'Marker','x',...
    'LineWidth',2,...
    'Color',[1 0 0]);


% Create xlabel
xlabel({'K_{arrival} (packets/sec)'});

% Create ylabel
ylabel({'Contention Overhead (%)'});

% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[20 100]);

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',21,'LineWidth',1.5);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.211160668092114 0.685238095238096 0.332142857142857 0.194047619047619]);
savefig(strcat(path, myTitle, '.fig'));
%saveas(gcf, strcat(path, myTitle, '.bmp'));

